version: '2.17.3'

services:
  mysql:
    image: 'mysql:8.0.3'
    restart: always
    ports:
      - 3307:3306
    volumes:
      - mysql_data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=biblionodejs
      - MYSQL_USER=root
      - MYSQL_PORT=3306
volumes:
  mysql_data:
